### DISCUSSION TITLE
Adding `APOC` to Neo4J via Docker Compose

### DISCUSSION THREAD

**Discussion by VoLKyyyOG** [amundsen-io/amundsen#1801] [Q&A] [answered]
Hey all!

New to Amundsen and `docker-compose`. I was wondering how one might install `APOC` for `Neo4J server` in the `docker-amundsen.yml`. I'm picking up an existing code base and working on exporting the backend database.

I understand that the installation steps are here:

- https://neo4j.com/labs/apoc/4.1/installation/#neo4j-server
- https://neo4j.com/developer/docker/

I then modified the existing `docker-amundsen.yml` to include:

```yaml
      ...
      container_name: neo4j_amundsen
      environment:
        - NEO4J_AUTH=...
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
        - NEO4JLABS_PLUGINS='["apoc"]'
      ulimits:
      ...
      volumes:
          - ./example/docker/neo4j/conf:/var/lib/neo4j/conf:Z
          - ./example/docker/neo4j/plugins:/var/lib/neo4j/plugins:Z
          - ./example/backup:/backup:Z
          - neo4j_data:/data
```
AFAIK, the `:Z` in `volumes` is used here to map our bastions.

Relevant Information: 
- Amundsen Neo4J Server Version: 3.5.26 
- This means I need APOC Version 3.5.0.11

Current Steps:
1. Once saved, I ran `docker-compose -f PATH_TO_THE_YML up` and launched the Neo4J UI via `http://localhost:7474/browser`. 
2. Logged in with the specified credentials (i.e default `neo4j` and `test`) and ran a query which worked.
3. I then tried to call the `apoc` package with `CALL apoc.help('keyword')` but it returns error `Neo.ClientError.Procedure.ProcedureNotFound` -> `There is no procedure with the name apoc.help registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`

I have a hunch its something to do with `volumes` and the `plugins` not being properly specified, though, I'm not there in figuring out the root cause.

Would appreciate any guidance or pointers. 

Cheers!
