### ISSUE TITLE
when frontend calls the metadata service, it keeps on redirecting to Keycloak for Authentication, even if valid token is passed

### ISSUE THREAD

**Issue by Milanmangar** [amundsen-io/amundsen#1118]
I am new to Amundsen. I am trying to get OIDC authentication with keycloak.
I have made the Authentication setup and have gotten frontend to interact with Keycloak and log in is working fine.
But for some reason when frontend calls the metadata service, it keeps on giving redirects to Keycloak for Authentication.

log says

```
amundsenmetadata    | 2021-05-18T13:36:36+0000.278 [DEBUG] __init__._before_request:59 (9:Thread-16) - Request Path: /user/admin
amundsenmetadata    | 2021-05-18T13:36:36+0000.278 [DEBUG] __init__._before_request:60 (9:Thread-16) - Request Endpoint: api.userdetailapi
amundsenmetadata    | 2021-05-18T13:36:36+0000.279 [DEBUG] __init__._before_request:61 (9:Thread-16) - Whitelisted Endpoint: status,healthcheck,health
amundsenmetadata    | 2021-05-18T13:36:36+0000.303 [INFO] _internal._log:122 (9:Thread-12) - 172.18.0.7 - - [18/May/2021 13:36:36] "GET /user/admin/follow/ HTTP/1.1" 302 -
amundsenfrontend    | 2021-05-18T13:36:36+0000.308 [DEBUG] connectionpool._make_request:461 (1:Thread-34) - http://amundsenmetadata:5002 "GET /user/admin/follow/ HTTP/1.1" 302 1251
amundsenmetadata    | 2021-05-18T13:36:36+0000.310 [INFO] _internal._log:122 (9:Thread-13) - 172.18.0.7 - - [18/May/2021 13:36:36] "GET /latest_updated_ts HTTP/1.1" 302 -
amundsenfrontend    | 2021-05-18T13:36:36+0000.318 [DEBUG] connectionpool._new_conn:231 (1:Thread-34) - Starting new HTTP connection (1): key_cloak_con:8080
amundsenfrontend    | 2021-05-18T13:36:36+0000.321 [DEBUG] connectionpool._make_request:461 (1:Thread-37) - http://amundsenmetadata:5002 "GET /latest_updated_ts HTTP/1.1" 302 1239
amundsenmetadata    | 2021-05-18T13:36:36+0000.328 [INFO] _internal._log:122 (9:Thread-15) - 172.18.0.7 - - [18/May/2021 13:36:36] "GET /tags/ HTTP/1.1" 302 -
amundsenfrontend    | 2021-05-18T13:36:36+0000.329 [DEBUG] connectionpool._new_conn:231 (1:Thread-37) - Starting new HTTP connection (1): key_cloak_con:8080
amundsenfrontend    | 2021-05-18T13:36:36+0000.333 [DEBUG] connectionpool._make_request:461 (1:Thread-35) - http://amundsenmetadata:5002 "GET /tags/ HTTP/1.1" 302 1203
amundsenmetadata    | 2021-05-18T13:36:36+0000.343 [INFO] _internal._log:122 (9:Thread-14) - 172.18.0.7 - - [18/May/2021 13:36:36] "GET /popular_tables/?limit=4 HTTP/1.1" 302 -
amundsenfrontend    | 2021-05-18T13:36:36+0000.348 [DEBUG] connectionpool._new_conn:231 (1:Thread-35) - Starting new HTTP connection (1): key_cloak_con:8080
amundsenfrontend    | 2021-05-18T13:36:36+0000.352 [DEBUG] connectionpool._make_request:461 (1:Thread-36) - http://amundsenmetadata:5002 "GET /popular_tables/?limit=4 HTTP/1.1" 302 1267
amundsenfrontend    | 2021-05-18T13:36:36+0000.357 [DEBUG] connectionpool._make_request:461 (1:Thread-34) - http://key_cloak_con:8080 "GET /auth/realms/master/protocol/openid-connect/auth?client_id=amundsen-frontend&redirect_uri=http%3A%2F%2Famundsenmetadata%3A5002%2Foidc_callback&scope=openid+email&access_type=offline&response_type=code&state=eyJjc3JmX3Rva2VuIjogIldST0dzcG5hTGg0T05iQVdZRkF2WDMxQlp1ZXJYNkdxIiwgImRlc3RpbmF0aW9uIjogImV5SmhiR2NpT2lKSVV6STFOaUo5LkltaDBkSEE2THk5aGJYVnVaSE5sYm0xbGRHRmtZWFJoT2pVd01ESXZkWE5sY2k5aFpHMXBiaTltYjJ4c2IzY3ZJZy5vOUNVQWVvMWZkWjVVd0Y4a0J5a3FqQ28wS0RYRVc1Z3NQaW5MSjVENXVrIn0%3D HTTP/1.1" 400 2567
```

docker-compose.yml looks like

```
amundsenmetadata:
    build:
      context: ./amundsenmetadatalibrary
      dockerfile: public.Dockerfile
    container_name: amundsenmetadata
    stdin_open: true
    tty: true
    depends_on:
      - neo4j
    ports:
      - 5002:5002
    networks:
      - amundsen_net
    environment:
      - PROXY_HOST=bolt://neo4j_amundsen
      - FLASK_APP_MODULE_NAME=flaskoidc
      - FLASK_APP_CLASS_NAME=FlaskOIDC
      - SQLALCHEMY_DATABASE_URI=sqlite:///sessions.db
      - FLASK_OIDC_SQLALCHEMY_DATABASE_URI=sqlite:///sessions.db
      - OIDC_CLIENT_SECRETS=./client_secrets.json
  amundsenfrontend:
      build:
        context: ./amundsenfrontendlibrary
        args:
          SEARCHSERVICE_BASE: http://amundsensearch:5001
          METADATASERVICE_BASE: http://amundsenmetadata:5002
        dockerfile: public.Dockerfile
      container_name: amundsenfrontend
      ports:
        - 5000:5000
      networks:
        - amundsen_net
      depends_on:
        - amundsenmetadata
        - amundsensearch
      environment:
        - SEARCHSERVICE_BASE=http://amundsensearch:5001
        - METADATASERVICE_BASE=http://amundsenmetadata:5002
        - FRONTEND_SVC_CONFIG_MODULE_CLASS=amundsen_application.oidc_config.OidcConfig
        - APP_WRAPPER=flaskoidc
        - APP_WRAPPER_CLASS=FlaskOIDC
        - SQLALCHEMY_DATABASE_URI=sqlite:///sessions.db
        - SESSION_TYPE=sqlalchemy
        - FLASK_OIDC_SECRET_KEY=base-flask-oidc-secret-key
        - FLASK_OIDC_WHITELISTED_ENDPOINTS=status,healthcheck,health
        - FLASK_OIDC_LOG_DATE_FORMAT=%Y-%m-%dT%H:%M:%S%z
        - FLASK_OIDC_LOG_LEVEL=INFO
        - OIDC_CLIENT_SECRETS=./client_secrets.json
```

client_secrets.json for frontent, metadata service, search service is same

```
{
    "web": {
        "issuer": "http://localhost:8080/auth/realms/master",
        "issuer_admin": "http://localhost:8080/auth/admin/realms/master",
        "auth_uri": "http://localhost:8080/auth/realms/master/protocol/openid-connect/auth",
        "client_id": "amundsen-frontend",
        "client_secret": "eb15te11-0b9d-90e5-v98a-43901dk26d8g",
        "userinfo_uri": "http://key_cloak_con:8080/auth/realms/master/protocol/openid-connect/userinfo",
        "token_uri": "http://key_cloak_con:8080/auth/realms/master/protocol/openid-connect/token",
        "token_introspection_uri": "http://key_cloak_con:8080/auth/realms/master/protocol/openid-connect/token/introspect",
	      "redirectUris": ["http://localhost:5000/*"]
	}
}

```

It happens in all the endpoints. It redirects (giving code 302) and gives error with code 400, i have verified token is being passed in headers. Please help me fix it.

Thanks in advance!

## Expected Behavior

If the token is valid, it should not be redirected to keycloak for authentication.

## Current Behavior

Even if the token is valid, it is redirecting to keycloak for authentication.

## Steps to Reproduce

1. follow instruction for OIDC Authentication in [https://www.amundsen.io/amundsen/authentication/oidc/](url) and [https://nirav-langaliya.medium.com/setup-oidc-authentication-with-lyft-amundsen-via-okta-eb0b89d724d3](url)
2. Try logging in. Log in will work fine but Metadata service will be redirected to keycloak authentication endpoint.

## Context

Not able to connect with metadata service and search service, when OIDC Authentication is configured, due to inter microservice authenticatoin issue.
