### ISSUE TITLE
AWS Amazon OpenSearch Service endpoint format

### ISSUE THREAD

**Issue by ecc256** [amundsen-io/amundsen#1583]
Guys,
Need a little help here.
What would be the right endpoint format for helm deployment with _**AWS Amazon OpenSearch Service (successor to Amazon Elasticsearch Service)**_?
The latter is in VPC, allows connect from local subnets only, w/o auth and allows http.
It's helm3 if it matters.

```
elasticsearch:
  enabled: false

search:
  # Proxy information needed for the search
  proxy:
    # search.proxy.endpoint -- Endpoint of the search proxy (i.e., ES endpoint etc.)
    # You should only need to change this, if you don't use the version in this chart.
    endpoint: "http://<name>.us-east-1.es.amazonaws.com"
    endpoint: "http://<name>.us-east-1.es.amazonaws.com:80"
    endpoint: "<name>.us-east-1.es.amazonaws.com:80"
```
