### ISSUE TITLE
import_string() failed for 'metadata_service.oidc_config.OidcConfig

### ISSUE THREAD

**Issue by ayush-san** [amundsen-io/amundsen#580]
I am trying to enable OIDC for amundsen. When testing it on local with the following docker images and environment variable I am getting `import_string() failed for 'metadata_service.oidc_config.OidcConfig'.` due to `ModuleNotFoundError: No module named 'amundsen_application'` in amundsenmetadata process.

```
amundsenmetadata:
      image: amundsendev/amundsen-metadata-oidc:2.5.4
      environment:
         - PROXY_HOST=bolt://neo4j_amundsen
         - FLASK_OIDC_CLIENT_SECRETS=/app/client_secrets.json
         - METADATA_SVC_CONFIG_MODULE_CLASS=metadata_service.oidc_config.OidcConfig
         - FLASK_APP_MODULE_NAME=flaskoidc
         - FLASK_APP_CLASS_NAME=FlaskOIDC

amundsenfrontend
      image: amundsendev/amundsen-frontend-oidc:2.2.0
      environment:
        - SEARCHSERVICE_BASE=http://amundsensearch:5001
        - METADATASERVICE_BASE=http://amundsenmetadata:5002
        - FLASK_OIDC_CLIENT_SECRETS=/app/client_secrets.json
        - FRONTEND_SVC_CONFIG_MODULE_CLASS=amundsen_application.oidc_config.OidcConfig
        - APP_WRAPPER=flaskoidc
        - APP_WRAPPER_CLASS=FlaskOIDC
        - FLASK_OIDC_WHITELISTED_ENDPOINTS=status,healthcheck,health

amundsensearch
      image: amundsendev/amundsen-search:2.4.0
```

## Expected Behavior
I have followed [authentication.md](https://github.com/lyft/amundsen/blob/master/docs/authentication/oidc.md) to enable oidc authentication but skipped setting flask oidc variable for search service since it doesn't have flaskoidc module. 

## Current Behavior
I am getting `ModuleNotFoundError: No module named 'amundsen_application'` in OidcConfig of amundsenmetadatalibrary. 

OidcConfig of amundsenmetadatalibrary is trying to import package amundsen_application which is defined in amundsenfrontendlibrary. I think this is a bug since amundsenmetadatalibrary does not have `amundsen_application` package but it trying to [import it](https://github.com/lyft/amundsenmetadatalibrary/blob/48dfa0550d7e90e09a689ecda85d997dc28b8af2/metadata_service/oidc_config.py#L7)

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/57655135/88516269-a1249100-d00a-11ea-8b9d-ed6eb6b6d809.png)

## Your Environment
* amundsenmetadata: amundsendev/amundsen-metadata-oidc:2.5.4
* amundsenfrontend: amundsendev/amundsen-frontend-oidc:2.2.0
* amundsensearch: amundsendev/amundsen-search:2.4.0

**Comment by feng-tao** [comment]
cc @verdan 
Verdan, let me know if you could take a look.

**Comment by verdan** [comment]
@ayush-san I agree, this should not be the case. I think we just copied the same file in metadata service. 
And the truth is, you don't even need a separate OIDC file in the metadata. We simply need this for frontend to generate and pass the authorization headers, and the other microservices just utilize them and validate them. 
Could you please open a PR with a fix ?
```
amundsenmetadata:
      image: amundsendev/amundsen-metadata-oidc:2.5.4
      environment:
         - PROXY_HOST=bolt://neo4j_amundsen
         - FLASK_OIDC_CLIENT_SECRETS=/app/client_secrets.json
         - FLASK_APP_MODULE_NAME=flaskoidc
         - FLASK_APP_CLASS_NAME=FlaskOIDC
```
