### ISSUE TITLE
ModuleNotFoundError: No module named 'flaskoidc' in Amundsen FrontEnd docker

### ISSUE THREAD

**Issue by pacobuenaparte** [amundsen-io/amundsen#813]
## Current Behavior
I used helm to deploy Amundsen. I set `oidcEnabled: true`, I provide a config-oidc secret with my keycloak OIDC settings, but the amundsen-frontend pod can not start because of a:
`ModuleNotFoundError: No module named 'flaskoidc' in Amundsen FrontEnd docker 
`

## Steps to Reproduce
1. Use the helm chart with oidcEnabled: true
2. provide your config-oidc

## Screenshots (if appropriate)
![Screenshot from 2020-11-13 05-46-52](https://user-images.githubusercontent.com/17688116/99029772-ab47ac80-2573-11eb-81f9-229693041fd2.png)

## Your Environment

* Amunsen version used: 2.3.0 and 3.0.0 for the docker front-end
* Deployment (k8s or native): k8s
* Deployment env variables:
```
          env:
            - name: FRONTEND_BASE
              value: 'https://amundsen.polynom.io'
            - name: SEARCHSERVICE_BASE
              value: 'http://amundsen-search:5001'
            - name: METADATASERVICE_BASE
              value: 'http://amundsen-metadata:5002'
            - name: LONG_RANDOM_STRING
              value: '1234'
            - name: FRONTEND_SVC_CONFIG_MODULE_CLASS
              value: amundsen_application.oidc_config.OidcConfig
            - name: FLASK_OIDC_WHITELISTED_ENDPOINTS
              value: 'status,healthcheck,health'
            - name: FLASK_OIDC_SQLALCHEMY_DATABASE_URI
              value: 'sqlite:///sessions.db'
            - name: APP_WRAPPER
              value: flaskoidc
            - name: APP_WRAPPER_CLASS
              value: FlaskOIDC
            - name: FLASK_OIDC_CLIENT_SECRETS
              value: /etc/client_secrets.json
            - name: FLASK_OIDC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: oidc-config
                  key: OIDC_CLIENT_SECRET
```
